### DISCUSSION TITLE
Shouldn't I see an entity for the bluetooth_proxy and/or esp32_ble_tracker?

### DISCUSSION THREAD

**Discussion by TRSx80** [agittins/bermuda#547] [Q&A]
I am not sure if this is working or not.

I enabled `VERBOSE` logging, and then a `text_sensor` (because otherwise, I couldn't see _anything_) but now that is the only entity that I can see for this device.

I can see a bunch of BLE adverts flying by, both in the device logs as well as that `test_sensor`, so I think it is working at least in some sense.

But aren't there supposed to be any entities for the `bluetooth_proxy` and/or `esp32_ble_tracker`?

Here is the full config:

<details>

``` yaml
esphome:
  name: not-esp-002
  friendly_name: not-esp-002

esp32:
  board: esp32dev
  framework:
    # recommended instead for Bluetooth proxying (per Bermuda)
    type: esp-idf
    #type: arduino

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: <redacted>

ota:
  password: <redacted>
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #ap:
  #  ssid: "Not-Esp-002 Fallback Hotspot"
  #  password: <redacted>

#captive_portal:

bluetooth_proxy:
  active: true  # allows outbound connections from HA to devices.

esp32_ble_tracker:
  scan_parameters:
    active: true # Whether to send scan-request packets to devices to gather more info (like devicename)
    interval: 211ms # suggested 211ms # default 320ms
    window: 120ms # suggested 120ms # default 30ms

text_sensor:
  - platform: ble_scanner
    name: "BLE Devices Scanner"
```

</details>
