### DISCUSSION TITLE
Controlling Android iBeacon adverts when away from home

### DISCUSSION THREAD

**Discussion by agittins** [agittins/bermuda#554] [The Bermuda Cookbook]
Share your recipes below!

The Android Homeassistant Companion App has a "Bluetooth Transmitter" feature that broadcasts an iBeacon advertisement. This is one of the best ways to ensure your phone is detectable in Bermuda (either with or without IRK's in the "Private BLE Device" integration), and it allows you to adjust the advertising interval and transmit power as well (Medium or High power is often required for reliable detection, and 3Hz is a good balance for advertising interval).

But having your phone always sending out a static iBeacon advertisement can pose a privacy risk, in that your phone is uniquely identifiable when out and about. You might also be concerned about battery usage (I've not tested this, but I suspect that BLE adverts are a tiny, tiny percentage of the battery consumption on a mobile phone, but YMMV).

## The built-in solution

The HA companion app offers a "Transmit only when on home network" option, which certainly helps and might do everything you need. A few folk have found it doesn't always cover every situation:

- You might have multiple places (networks) where you might want the adverts enabled
- Sometimes it might just not work (some have found the transmitter still turned off after being at home for some time)
- You might want Bermuda to spot you *before* you are within WiFi range (say you have a proxy at the end of a driveway etc)

## Other options

You can control the Bluetooth Transmitter in the companion app using notifications. This can enable you to do things like:

- Use your phone's geolocation abilities, and create an automation that turns the transmitter on and off based on your phone entering/leaving your home `Zone`. Or you could create a larger zone around the home, so that there is more likely to be time for the phone to update its location by the time you reach home.
  - This means that your phone will be transmitting already before you reach home, which might give the best chance for triggering arrival notifications as promptly as possible.
- Use different rules for turning Off versus turning On. EG:
  - You might turn the transmitter off after your phone has been attached to your car's bluetooth for 2 minutes (or immediately if you want to have departure automations happen faster).
  - Automate turning the transmitter On based on geolocation, or maybe trigger it from seeing a *neighbours* wifi on the way!
- You can also adjust the transmit power and interval from automations (using the app's notifications). So you might set transmit power to the highest level when your phone detects you are getting close to home (for maximum arrival-automation-responsiveness), and then after you are detected as at `Home` for several minutes, adjust the power down to a level that still gives reliable area detection.

## Controlling Bluetooth Transmitter in automations

See [BLE Beacon Transmitter](https://companion.home-assistant.io/docs/notifications/notification-commands#ble-beacon-transmitter) in the notifcations commands section of the Companion App docs for the full details, here are examples from that page on how to turn the transmitter off and alter power level, respectively:

```yaml
automation:
  - alias: Turn off BLE transmitter
    trigger:
      ...
    action:
      - action: notify.mobile_app_<your_device_id_here>
        data:
          message: "command_ble_transmitter"
          data:
            command: "turn_off"
```

```yaml
automation:
  - alias: Change Transmit Power BLE transmitter
    trigger:
      ...
    action:
      - action: notify.mobile_app_<your_device_id_here>
        data:
          message: "command_ble_transmitter"
          data:
            command: "ble_set_transmit_power"
            ble_transmit: "ble_transmit_high"
```

## Recipes

Please feel free to contribute your particular recipes below!
