### DISCUSSION TITLE
Espressif C6 proxy configuration [was: Amendments for Wiki's ESP-Home configuration page]

### DISCUSSION THREAD

**Discussion by retrography** [agittins/bermuda#572] [Q&A]
One correction: It is mentioned, by mistake, that C6 is dual-core. It is not. It is single-core, just like C3.

A couple amendments:

1. I am using C6 as a proxy and for now it works like a charm. It requires quite some manual config. See below:

```yaml
substitutions:
  device_name: "btproxy-bathroom"

esphome:
  name: ${device_name}
  friendly_name: Bluetooth Proxy - Bathroom
  platformio_options:
    board_build.mcu: esp32c6
    board_build.variant: esp32c6
    board_build.flash_mode: dio   

esp32:
  board: esp32-c6-devkitm-1 # Could be devkitc, depending on the model
  variant: esp32c6
  flash_size: 4MB # Could be 8 or 16, depending on the model
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"    
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

sensor:
  - platform: uptime
    # The uptime sensor is extremely helpful to know if your device is rebooting
    # when it shouldn't be. This might indicate your interval-to-window timing is
    # too tight, and the window needs to be reduced.
    name: "Uptime Sensor"
    update_interval: 60s

logger:
  baud_rate: 0
    
api:
  encryption:
    key: XXXXX

ota:
  platform: esphome
  password: XXXXX

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${device_name}
    password: XXXXX

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true
   
button:
  - platform: safe_mode
    name: ${device_name} (Safe Mode)
  
captive_portal:
```

2. Theoretically,  S3 should work great as a BT proxy, with ample resources. In reality, it installs well after sufficient tinkering with setup, but Bermuda never recognizes it as a proxy. Below is my setup that seemingly works, but is never recognized.

```yaml
esphome:
  name: "btproxy-test-s3"
  friendly_name: "btproxy-test-s3"
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
    board_build.variant: esp32s3

esp32:
  board: esp32-s3-devkitm-1 # Depending on the model, can be devkitc as well
  variant: esp32s3
  flash_size: 4MB # Depending on the model
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ENABLE_ESP32_BLE_CONTROLLER: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

psram: # I have heard octal and 120MHz may also work on better-endowed editions
  mode: quad
  speed: 80MHz

# Enable logging
logger:

api:
  encryption:
    key: XXXXX

ota:
  - platform: esphome
    password: XXXXX

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${device_name}
    password: XXXXXX

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true
  
captive_portal:
```

**Comment by agittins** [comment]
Hi! Sorry for the very slow response!

> One correction: It is mentioned, by mistake, that C6 is dual-core. It is not. It is single-core, just like C3.

I grabbed that info from wikipedia, so just checked https://www.espressif.com/en/products/socs/esp32-c6 and it says:
> It consists of a high-performance (HP) 32-bit RISC-V processor, which can be clocked up to 160 MHz, and a low-power (LP) 32-bit RISC-V processor, which can be clocked up to 20 MHz.

I notice they don't explicitly use the term "dual core" but nor do they state "single core", which they do on the C3 literature. I have to admit the line-up is so confusing - I can never remember c3 vs s3 vs c2 vs s2 etc!

> I am using C6 as a proxy and for now it works like a charm. It requires quite some manual config. See below:

Fantastic, thanks! When I get a moment I'll put this into the wiki and the repo I'm putting together for packaged configs.

> Theoretically, S3 should work great as a BT proxy, with ample resources. In reality, it installs well after sufficient tinkering with setup, but Bermuda never recognizes it as a proxy. Below is my setup that seemingly works, but is never recognized.

I have a user-contributed config for S3 that apparently works, you can find it at https://github.com/agittins/bermuda-proxies/

What do you mean by not recognised? Does it show up in esphome? Or the new bluetooth integration pages? If it is working as a standard esphome bluetooth proxy then Bermuda should recognise it - or is it perhaps recognised but it is just not sending any actual advertisements? Bermuda might only look up a proxy after it gets an advert from it via the bluetooth backend, I'm not sure off the top of my head.

**Comment by agittins** [comment]
Howdy - I've added a link to this post from the wiki page for setting up the c6, and I changed the description of the architecture (whether I made it better or not I am not entirely sure! 🤣 )

Given the level of config required for the C6 I've noted it as "experimental" and just linked it to here, hopefully that way folk trying it out can contribute updates as things progress. I think I might convert this issue to a discussion as well, since that might be the better place for it now.

Cheers!

**Comment by MStapelfeldt** [comment]
@retrography 
> 1. I am using C6 as a proxy and for now it works like a charm. It requires quite some manual config. See below:

I tried to use the yaml with a C6 and get the errors:
```
Platform Manager: Installing https://github.com/pioarduino/platform-espressif32/releases/download/6.09.00/platform-espressif32.zip
INFO Installing https://github.com/pioarduino/platform-espressif32/releases/download/6.09.00/platform-espressif32.zip
WARNING Package download failed: Got the unrecognized status code '404' when downloaded https://github.com/pioarduino/platform-espressif32/releases/download/6.09.00/platform-espressif32.zip. Retrying... (attempt 1/3)
WARNING Package download failed: Got the unrecognized status code '404' when downloaded https://github.com/pioarduino/platform-espressif32/releases/download/6.09.00/platform-espressif32.zip. Retrying... (attempt 2/3)
PackageException: Got the unrecognized status code '404' when downloaded https://github.com/pioarduino/platform-espressif32/releases/download/6.09.00/platform-espressif32.zip
```
I think there was a bigger change in how to use C6 with Bermuda. Maybe you can help and update your full example yaml?

**Comment by tboby** [comment]
@agittins 
I just got 5 DFR1117 (https://wiki.dfrobot.com/dfr1117/), and set the first one up with:
```
esphome:
  name: beetle-c6--one
  friendly_name: Beetle C6 - One

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    interval: 320ms
    window: 300ms

bluetooth_proxy:
  active: true
```

If I wave my phone around in front of it, I see the unfiltered distance update every second. WiFi logs appear to be fine.

I'm afraid I'm not quite sure what the measure for "Compatibility" is. E.g. I've been playing with an M5 Atom S3 + Echo Base and noted that I was running into out of memory issues when trying to run a voice pipeline alongside the bluetooth scanning, but the BLE scanning was always rock solid.

These boards don't have any sensors so I don't have anything obvious to test alongside, but I generated a little set of BLE counters and used web_server to try and get a sense of whether the C6 is struggling. The web server updates logs/sensors every second while continuing to send to the api, even with an interval of 100ms, window 90ms or even 100ms (100% duty cycle!?). It reports loop time <25ms (usually more like 15ms) and the chip doesn't feel particularly warm. I even set it to 5s interval, 4s window, and everything seemed fine.

I'm also not sure if any of the defaults in the proxies repo are crucial to bermuda, but the very simple config above seems to be working fine. Happy to test anything else if I'm missing something :)
