### ISSUE TITLE
Area Radius not using meters when HA system default is feet 

### ISSUE THREAD

**Issue by asucrews** [agittins/bermuda#201]
When I set the area to 10 meters (30 feet), areas farther than 10 feet away become unknown. When I set the area to 25 meters (75 feet), the unknown areas reappear.

My house is neither 25 meters nor even 10 meters long or wide, so I believe there might be an issue with the conversion from meters to feet.

HA Versions
Core: 2024.5.4
Supervisor: 2024.05.1
Operating System: 12.3
Frontend: 20240501.1
Bermuda
Version: 0.6.6

I'm not sure how to retrieve the logs for this issue.

**Comment by agittins** [comment]
Hmm that's odd. Can you post a screenshot of your config page (in bermuda configuration, global options)?

There might be something odd going on with the config option conversion. Internally, Bermuda uses metres for everything, and the sensors are exposed with a "native measurement" of metres, so the frontend will be doing the conversion to feet for you.

But I have a feeling it doesn't convert the config page, because I don't think I can (or have?) told HA the units for those settings. Or maybe it does and I don't realise it!

My expectation is that you need to enter metres on the config page, but HA will translate the units for sensors etc - but I might need to take a look at that specifically, by the sounds of it. A screenshot of your config just so I can see what it's reflecting would be good.

Also, could you post one of the "options" sections from calling the `dump_devices` service (Developer Tools, Services, `bermuda.dump_devices`). There will be one in every "block", it will look a bit like:

```yaml
  options:
    attenuation: 3
    devtracker_nothome_timeout: 180
    max_area_radius: 72
    max_velocity: 3
    ref_power: -55
    smoothing_samples: 25
    update_interval: 10
    configured_devices:
      - C7:B8:C6:B0:27:11
      - EE:E8:37:9F:6B:54
      - CE12CBEB2DBE448BB057C1FE9804B45F_100_1
      - A4:C1:38:DC:19:36
      - FF:FF:10:F7:A4:B9
      - A4:C1:38:3E:4F:A4
      - 5A:B6:51:70:6C:3B
```

That plus the screenshot should show if anything is doing any conversion of units at the config end of things.

By the way, I set my radius to 70 metres or so (effectively infinite, since ble rarely travels that far) as I've found little benefit in having the sensors go to unknown, I'd rather they snap to the nearest sensor even if it's not "right". But that doesn't address the conversion issue you're seeing, of course...

**Comment by asucrews** [comment]
I totally agree with you on the very little benefit of a scanner going unknow, but to each there own.  that why i wanted to set mine to 25 meters, that should about 75 feet. let me know if you need anything else.

![image](https://github.com/agittins/bermuda/assets/5163575/e475f760-6486-4a06-90de-44748b172dd2)


```
      options:
        attenuation: 3
        devtracker_nothome_timeout: 30
        max_area_radius: 50
        max_velocity: 3
        ref_power: -51
        smoothing_samples: 20
        update_interval: 10
```
