### ISSUE TITLE
Entities not leaving Unavailable state until after integration reload

### ISSUE THREAD

**Issue by walberjunior** [agittins/bermuda#235]
## Version of the custom_component
Burmuda v0.6.7

## Configuration

HA:
Core2024.6.4
Supervisor2024.06.2
Operating System12.4
Frontend20240610.1
Esphome 2024.6.6

esphome config:
```
bluetooth_proxy:
  active: True

esp32_ble_tracker:
  scan_parameters:
    interval: 320ms
    window: 300ms
```

## Describe the bug

If the device to be tracked is out of range of the esp board when restarting the HA, the entity remains unavailable until the integration is manually reloaded.

![image (11)](https://github.com/agittins/bermuda/assets/20650850/60e61421-78b1-41e2-9518-7fa133bff36d)
![image](https://github.com/agittins/bermuda/assets/20650850/7022949e-048e-4519-a155-e048a2d49117)

## Debug log

```
30:ae:xx:xx:xx:34:
  name: display_proxy
  local_name: null
  prefname: null
  address: 30:ae:xx:xx:xx:34
  options:
    attenuation: 3
    devtracker_nothome_timeout: 30
    max_area_radius: 20
    max_velocity: 3
    ref_power: -55
    smoothing_samples: 20
    update_interval: 10
    configured_devices:
      - D1419F0xxxxxxxxxx7958_100_40004
  unique_id: 30:ae:xx:xx:xx:34
  address_type: bd_addr_type_unknown
  area_id: frente
  area_name: Frente
  area_distance: null
  area_rssi: null
  area_scanner: null
  zone: not_home
  manufacturer: null
  connectable: false
  is_scanner: true
  beacon_type: []
  beacon_sources: []
  beacon_unique_id: null
  beacon_uuid: null
  beacon_major: null
  beacon_minor: null
  beacon_power: null
  entry_id: 2dafa38xxxxxxxxxaf01a1dc3ff8
  create_sensor: false
  create_sensor_done: false
  create_tracker_done: false
  last_seen: 0
  scanners: {}
```
```
24:6f:xx:xx:xx:64:
  name: Cama
  local_name: null
  prefname: null
  address: 24:6f:xx:xx:xx:64
  options:
    attenuation: 3
    devtracker_nothome_timeout: 30
    max_area_radius: 20
    max_velocity: 3
    ref_power: -55
    smoothing_samples: 20
    update_interval: 10
    configured_devices:
      - D1419F0xxxxxxxxxx7958_100_40004
  unique_id: 24:6f:xx:xx:xx:64
  address_type: bd_addr_type_unknown
  area_id: bedroom
  area_name: Quarto
  area_distance: null
  area_rssi: null
  area_scanner: null
  zone: not_home
  manufacturer: null
  connectable: false
  is_scanner: true
  beacon_type: []
  beacon_sources: []
  beacon_unique_id: null
  beacon_uuid: null
  beacon_major: null
  beacon_minor: null
  beacon_power: null
  entry_id: 519388xxxxxxxxxxx15d22cb68c
  create_sensor: false
  create_sensor_done: false
  create_tracker_done: false
  last_seen: 0
  scanners: {}
```
```
94:e6:xx:xx:xx:28:
  name: Espgaragem
  local_name: null
  prefname: null
  address: 94:e6:xx:xx:xx:28
  options:
    attenuation: 3
    devtracker_nothome_timeout: 30
    max_area_radius: 20
    max_velocity: 3
    ref_power: -55
    smoothing_samples: 20
    update_interval: 10
    configured_devices:
      - D1419F0xxxxxxxxxx7958_100_40004
  unique_id: 94:e6:xx:xx:xx:28
  address_type: bd_addr_type_unknown
  area_id: garagem
  area_name: Garagem
  area_distance: null
  area_rssi: null
  area_scanner: null
  zone: not_home
  manufacturer: null
  connectable: false
  is_scanner: true
  beacon_type: []
  beacon_sources: []
  beacon_unique_id: null
  beacon_uuid: null
  beacon_major: null
  beacon_minor: null
  beacon_power: null
  entry_id: 6e4adddaebxxxxxxxxxxxxxxxxxxxf939ab9
  create_sensor: false
  create_sensor_done: false
  create_tracker_done: false
  last_seen: 0
  scanners: {}
```
