### ISSUE TITLE
Device frequently go to unkown state

### ISSUE THREAD

**Issue by ageurtse** [agittins/bermuda#331]
i have searched the forum over at homeassistant, looked into het trouble shouting seqtion but can't find a solution for my problem. 
The problem i have is that my iphone is very often go to unkown state, even if the phone isn't moved. 
it looks like it goes to that state after 30 till 60 seconds. 

i'm using ESP32S3

```
################################################################################
# Bluethooth tracker
################################################################################
bluetooth_proxy:

esp32_ble_tracker:
  scan_parameters:
    active: True
```

these are the config settings from within Bermuda
![afbeelding](https://github.com/user-attachments/assets/fef22380-08d9-477c-a8fd-e263a308915d)

and ofcourse the diagnostics
[config_entry-bermuda-01J4RYA69YPY6SS69ASGG9NBND.json](https://github.com/user-attachments/files/17480294/config_entry-bermuda-01J4RYA69YPY6SS69ASGG9NBND.json)
