### ISSUE TITLE
ESP32 Last Advertisement 2.5 million seconds ago

### ISSUE THREAD

**Issue by kloggy** [agittins/bermuda#382]
I have four Bluetooth Proxies all ESP32 based. Two of them do 'other stuff' and work fine whilst two of them are purely BT proxies and configured identically. Only one of those behaves as expected in Bermuda.

The only way to get Bermuda recognise one of them is to re-install the ESPHome config. It seems to work fine at that point but as soon as I power cycle the ESP32, Bermuda seems to know of it's existence but does not receive advertisements.

Here it is immediately after (re)installing from ESPHome
![image](https://github.com/user-attachments/assets/212f47f5-19df-475c-b76f-c2e8b07c0533)

Here it is after it is powered off (So far as expected)
![image](https://github.com/user-attachments/assets/5e07275f-6a98-4df2-af33-3e0beecfaa8e)

After a little time it changes to this
![image](https://github.com/user-attachments/assets/aa65a24c-4af4-4084-bf7a-c3a8b2a88cbb)

I have tried uninstalling and reinstalling Bermuda with HA restarts but the behaviour is always identical

Here is my ESPHome config, the only thing changing being the `name` and `friendly_name` substitutions
```
substitutions:
  name: "bluetooth-proxy-01-sitting-room"
  friendly_name: BT Proxy 01 (Sitting Room)

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  # Set up a wifi access point
  ap: {}

# Enable Home Assistant API
api:

# Enable logging
logger:

# Allow Over-The-Air updates
ota:
  platform: esphome

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true
    interval: 1000ms  # default is 320ms. Time spent per adv channel
    window: 900ms     # default is 30ms. Time spent listening during interval.

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
```

I have attached the diagnostics and hopefully you will be able to shed some light on this!
Thanks.
