### ISSUE TITLE
Amendments for Wiki's ESP-Home configuration page (https://github.com/agittins/bermuda/wiki/ESPHome-Configurations)

### ISSUE THREAD

**Issue by retrography** [agittins/bermuda#433]
One correction: It is mentioned, by mistake, that C6 is dual-core. It is not. It is single-core, just like C3.

A couple amendments:

1. I am running Bermuda on C6 and for now it works like a charm. It requires quite some manual config. See below:

```yaml
substitutions:
  device_name: "btproxy-bathroom"

esphome:
  name: ${device_name}
  friendly_name: Bluetooth Proxy - Bathroom
  platformio_options:
    board_build.mcu: esp32c6
    board_build.variant: esp32c6
    board_build.flash_mode: dio   
    build_flags: "-DI2C_NUM_1=I2C_NUM_0" 

esp32:
  board: esp32-c6-devkitm-1 # Could be devkitc, depending on the model
  variant: esp32c6
  flash_size: 4MB # Could be 8 or 16, depending on the model
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"    
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

sensor:
  - platform: uptime
    # The uptime sensor is extremely helpful to know if your device is rebooting
    # when it shouldn't be. This might indicate your interval-to-window timing is
    # too tight, and the window needs to be reduced.
    name: "Uptime Sensor"
    update_interval: 60s

logger:
  baud_rate: 0
    
api:
  encryption:
    key: XXXXX

ota:
  platform: esphome
  password: XXXXX

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${device_name}
    password: XXXXX

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true
   
button:
  - platform: safe_mode
    name: ${device_name} (Safe Mode)
  
captive_portal:
```

2. Theoretically, Bermuda should work great on S3 with ample resources. In reality, it installs well after sufficient tinkering with setup, but Bermuda never recognizes it as a proxy. Below is my setup that seemingly works, but is never recognized.

```yaml
esphome:
  name: "btproxy-test-s3"
  friendly_name: "btproxy-test-s3"
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
    board_build.variant: esp32s3

esp32:
  board: esp32-s3-devkitm-1 # Depending on the model, can be devkitc as well
  variant: ESP32S3
  flash_size: 4MB # Depending on the model
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ENABLE_ESP32_BLE_CONTROLLER: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

psram: # I have heard octal and 120MHz may also work on better-endowed editions
  mode: quad
  speed: 80MHz

# Enable logging
logger:

api:
  encryption:
    key: XXXXX

ota:
  - platform: esphome
    password: XXXXX

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${device_name}
    password: XXXXXX

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true
  
captive_portal:
```
