### ISSUE TITLE
Support for ble_rssi esphome component

### ISSUE THREAD

**Issue by smhc** [agittins/bermuda#469]
**Is your feature request related to a problem? Please describe.**

The ble_rssi component seems to give more reliable and efficient measurements than "Private BLE Device". I am unsure why, but perhaps the IRK tracking is more reliable. Either way, it is more efficient as the edge devices only listen for specific devices and only report those, rather than reporting everything all the time.

**Describe the solution you'd like**

Support for ble_rssi as a "scanner":
https://esphome.io/components/sensor/ble_rssi.html

**Describe alternatives you've considered**

I have tried "Private BLE Device" but it does not appear to be very reliable compared to ble_rssi, even with the IRK registered. I am getting some readings, so it is working, but it regularly goes "unknown", missed readings, inaccurate etc. I think this is because "Private BLE device" only reports the signal strength to the nearest scanner instead of the strength to each scanner(?)

**Additional context**

**Comment by agittins** [comment]
Howdy!

The only thing that Bermuda uses Private BLE Device for is to find out what the current MAC address of the device is, other than that the advertisements etc are handled exactly the same as in every other device in Bermuda (so it gathers data from all scanners etc) - so the issue is unlikely to be related to Private BLE Device itself and more to the path between the proxy and HA/Bermuda.

It's interesting that you are getting better results from ble_rssi though. You're right that if you're only tracking one or several devices it does filter out the amount of traffic the esp32 needs to forward, but I've found esphome's proxy to be pretty solid once I'm using the right combination of tweaks (I haven't publicised it yet but I have packages I'm testing that include all the tweaks at https://github.com/agittins/bermuda-proxies that I'd suggest trying out).

I'd be very interested in seeing some possible data on the differences though. If it's significant I might consider building support for it but it would need to be a significant issue with the proxy method to justify the time on it, and I don't know how responsive it is (I expect it should be fine, but I haven't tried using native sensors as feeds for Bermuda, so not sure how it would perform).

If you have the time, would you mind experimenting/data gathering a bit? It'd be great to see a history graph with the ble_rssi and Bermuda's rssi sensors graphed together (you'll need to enable the hidden `nearest rssi` sensor from Bermuda on the device page in HA). It would be interesting to compare the plots between them for update frequency and values. Also if you could do a "download diagnostics" shortly after the history graph, that will let me see what the advert intervals etc are during that time.

Often people have trouble with the proxies missing adverts due to having the basic bluetooth-proxy setup on the esp32 rather than the tweaked settings, but I am interested to know if the ble_rssi stats really do perform better (I'll try and get a chance to test it myself as well).

**Comment by smhc** [comment]
You're right that I didn't have the correct config in some of the esp32-c3s, but I have fixed that now and still see better results with ble_rssi. If anything the tweaks just made ble_rssi work better.

I will attempt to gather some data. But what I will say is that quite often "Private BLE Device" doesn't "know" what the current MAC address is despite ble_rssi happily reporting the RSSI for the device from the same esp32 running both esp_proxy and esp32-tracker/ble_rssi. I assume this is what causes bermuda to lose track of the device, as it doesn't know what MAC to read. ble_rssi can work a lot harder trying to "find" the device and only report when it's worth doing so, without having to spam the world.

Perhaps I have something misconfigured, but even still, generic support for "signal strength" entities might be a cool feature regardless. I can envision using sound, light, wifi access points, heat etc. Anything that reports a signal strength and can be normalised to Bermuda's sense of distance could be used.

**Comment by smhc** [comment]
After some testing, perhaps there isn't a huge difference in RSSI readings. The screenshot shows "oscarbookshelf RSSI Tracker Pixel 7" as the ble_rssi sensor. Everything else is from "Private BLE" or Bermuda.

It is however a lot easier to reason about when you can see the RSSI readings across sensors simultaneously instead of only the "nearest". Despite the fact "oscarbookshelf" is the nearest scanner during this time and is getting a regular RSSI reading from both "Private BLE Device" and "ble_rssi", and yet the "distance" calculation is regularly "unknown". I think this is what led me to think ble_rssi would be better - but perhaps the issue is in Bermuda rather than the RSSI sensors.

![Image](https://github.com/user-attachments/assets/4a81b4b1-7aff-45e0-b025-96d810ef346d)

**Comment by agittins** [comment]
> I assume this is what causes bermuda to lose track of the device, as it doesn't know what MAC to read.

Correct, if Private BLE hasn't recognised it then Bermuda won't know which device it is (it will still see and track the bare MAC address as just a random device, it just won't be able to link it to the sensors for that phone etc.

> ble_rssi can work a lot harder trying to "find" the device and only report when it's worth doing so, without having to spam the world. I think this allows it's IRK logic to work better whilst Private BLE gets out of sync a bit?

I don't have data to back this up (yet?) but my gut instinct is that it might be the other way around. Doing the IRK stuff is computationally intensive - it has to look at every unique MAC address it sees, and run a cryptographic routine to see if it can decrypt the packet with the IRK. Compared to "read packet in, send packet out" it's a lot of work. So in my mind I'd expect it to be a lot more performant for the esp32 to simply forward on traffic, and let the comparatively massive cpu and memory in a ras pi or anything bigger do the intensive crypto work.

> generic support for "signal strength" entities 

Bermuda is very much tuned for working with RF propagation, but yes in theory that could be possible. Predator-style heatmaps for the win! 😆 


Great screenshot!

> a lot easier to reason about when you can see the RSSI readings across sensors simultaneously

Yes I use the history graphs a *lot* while trying to optimise the smoothing or working out what I've mangled in the code yet again. 😅 

So the Shelly's appear to be doing "okayish", but maybe they are losing packets due to distance, but Shelly's are also geared to be pretty conservative in their proxying so that it doesn't run the risk of doing worse at things Shelly ™ needs in order to avoid business problems (ie, being a bullet-proof light switch) .

The esp32, if it's really within 2m or so of the phone is *not* performing well. It looks like you're getting an update perhaps every 30 seconds, and sometimes not. This is why Bermuda is marking it unknown, because Bermuda (currently) has a 30 second timeout for the area/distance. The "unfiltered distance" and rssi sensors don't have that timeout, which is why you see a solid line from them even though there are no updates during that time.

Here's my Pixel 6 and the proxy in my studio, about 2.5m away from the phone:

![Image](https://github.com/user-attachments/assets/4698b06d-b70d-4e06-a866-29897c5c85dd)

Note the timescale here, pretty consistently getting an update every 1 second or 2 seconds (I have my update interval turned down to 2s, but that only affects delaying distance increase readings on the filtered distances, not decreasing distances, the unfiltered updates or the rssi).

The long flat lines on your rssi are periods where the esp32 is not sending any adverts, and some of these look like they might be... 5 minutes long? That seems to me that your esp32 is probably wedging up, and a watchdog inside the esp32 is kicking in to restart it (or a part of it). I think the bluetooth integration in HA can and does send restart commands to proxies that have stopped sending updates, so that might be what's happening there.

I think your esp32 is probably overloaded. I'd try commenting out all of the local ble_rssi stuff on your proxy, and anything else that might be taking up cpu time or memory (like pwm lights, or screens) and see if that gets you back to 1 second updates. Then you can try adding stuff back in. My guess is that local IRK might be pretty heavy, and it will be worse the more irk's you have on it - but it could be something else.

Feel free to share your full yaml if you'd like me to take a look at it.

**Comment by smhc** [comment]
Ok thanks, I hadn't considered the flat lines being lack of reports. I'm using the BLE transmitter with 1Hz frequency and "Medium" power, for now at least.

The esp32 is staying up ok, I have an uptime sensor and it didn't show any issue. However you may be right about it being overloaded, possibly from the ble_rssi component as you suggest. Especially as it's just a single core esp32-c3 knock off that may not be that powerful. (I was previously testing with an S3 and didn't consider the excessive cpu use). I guess it could be spending a lot of time doing AES operations and missing advertisements, especially as I had 3 devices registered so it had to check all 3 IRKs.

I removed the ble_rssi component and Bermuda's distance reports seems to be working a bit better. I'll post a screenshot once I get more data.

The yaml config is pretty basic, mostly from the FAQ:

```yaml
esphome:
  name: oscarbookshelf
  friendly_name: oscarbookshelf

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10" 


light:
  - platform: rgbw
    name: "BookshelfLight"
    red: red_output
    green: green_output
    blue: blue_output
    white: white_output
    color_interlock: True
    # Optional: Add effects
    effects:
      - random:
      - random:
          name: Random Effect With Custom Values
          transition_length: 5s
          update_interval: 7s

output:
  - platform: ledc
    id: red_output
    pin: 18
  - platform: ledc
    id: white_output
    pin: 19
  - platform: ledc
    id: green_output
    pin: 4
  - platform: ledc
    id: blue_output
    pin: 3

logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "B22222222222222xxxxxxx="
  on_client_connected:
     - esp32_ble_tracker.start_scan:
        continuous: true
  # Disable BLE tracking when there are no api connections live
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
      then:
        - esp32_ble_tracker.stop_scan:

ota:
  - platform: esphome
    password: "66xxxxxxxxxx91c6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  # RSSI based on Identity Resolving Key (IRK) - will disable this for a test
  - platform: ble_rssi
    irk: a1111111111111111111113
    name: "RSSI Tracker Pixel 7"
  # I had two others registered here..

esp32_ble_tracker:
  scan_parameters:
    continuous: False
    active: True  # will set this to false for testing
    interval: 320m
    window:   300ms
  - platform: uptime
    type: seconds
    name: Uptime Sensor
    update_interval: 60s
```

If this is the cause I won't be using ble_rssi, so my feature request can be closed from my perspective. Some people may wish to use it on more powerful chips, and I can certainly see use cases for using signal strength helpers that normalise some other source. So perhaps this could just be moved to a 'future plans' idea for supporting generic 'signal strength' sources from configurable entities.
